### ISSUE TITLE
Option to allow one instance only

### ISSUE THREAD

**Issue by g-rusev** [corvus-ch/rabbitmq-cli-consumer#22]
It would be great if in the config file there is an option that allows one instance only of the application.

If this option is set, and there is already a running application, not to allow a second instanse of the appliation (to quit).

This will be great in case we needs to have one consumer only.

**Comment by corvus-ch** [comment]
It is the goal of this project to stay focused as much as possible. In order to do so, when ever possible, things are delegated to tools which are better suited for the case.

In my opinion, task supervisors like Supervisord, Monit or SystemD and or init scripts for SysVinit, Upstart or the like are better suited for your use case.

**Comment by corvus-ch** [comment]
I assume that my previous comment answered the question. Therefore I close this issue. If this is premature, feel free to ask for a reopen.
