### ISSUE TITLE
Improve error message when failing to create a queue due to setting mismatch

### ISSUE THREAD

**Issue by a-ast** [corvus-ch/rabbitmq-cli-consumer#45]
I'm trying to run rabbitmq-cli-consumer from a docker container (image: 'thecodingmachine/php:7.2-v1-cli'):

rabbitmq-cli-consumer is taken as a binary from `rabbitmq-cli-consumer_2.3.0_linux_386.tar.gz`

When I run:
`./rabbitmq-cli-consumer --verbose --url amqp://guest:guest@rabbitmq --queue-name hello --executable worker.php`

this error message appears:
```
2018/10/18 23:31:56 failed to register a consumer: Exception (504) Reason: "channel/connection is not open"

**Comment by a-ast** [comment]
I've changed the queue name in publisher and now getting another error in the consumer
```
2018/10/18 23:59:26 Failed. Check error log for details.
2018/10/18 23:59:26 Error: fork/exec : no such file or directory
2018/10/18 23:59:26 Failed:
2018/10/18 23:59:26 Processed!
2018/10/18 23:59:26 Processing message...
```
and it never stops..

**Comment by maximium** [comment]
So can your connect to rabbitmq from the container with telnet?

**Comment by a-ast** [comment]
@maximium  I've managed to run the consumer script.
I've figured out that it always fails to listen for queues created as non-durable.

I'm yet very familiar with rabbitmq yet, so I don't how critical it is.
If you think that it is a normal behaviour, let's close my issue.

**Comment by corvus-ch** [comment]
By default, the consumer tries to create the queue. If the queue is already defined with different settings, this will fail. Since the consumer tries to create a durable queue and the existing queue was created as transient, this fails.

For this cases, the option `--no-declare` can be set to prevent the consumer from creating one.

Whats certainly bad here is the error message which by now way indicates what the actual issue is. This certainly needs to be improved.
